### ISSUE TITLE
PDF Data Extraction Using Gemini

### ISSUE THREAD

**Issue by santokalayil** [santokalayil/ai#4]
```python
from typing import List, Any
from pathlib import Path

from pydantic import BaseModel, Field
from IPython.display import Markdown, display
from google.genai.types import (
    FunctionDeclaration,
    GenerateContentConfig,
    Part,
    Tool,
    UserContent,
    ToolConfig,
    FunctionCallingConfig,
    Mode
)
from google import genai
import mimetypes

from sangemini.creds import GEMINI_API_KEY, GEMINI_MODEL_ID

import nest_asyncio
nest_asyncio.apply()



class MimeType(BaseModel):
    pdf: str = mimetypes.types_map.get('.pdf')
    json: str = mimetypes.types_map.get('.json')

mimetype = MimeType()

client = genai.Client(
    # vertexai=True, 
    # project=PROJECT_ID, 
    # location=LOCATION,
    api_key=GEMINI_API_KEY,
)


async def extract_pdf_content(pdf_path: Path, prompt: str, response_type: Any) -> Any:
    global client
    # client.aio.models.generate_content
    response = await client.aio.models.generate_content(
        model=GEMINI_MODEL_ID,
        contents=[
            Part.from_bytes(
                data=pdf_path.read_bytes(),
                mime_type=mimetype.pdf,
            ),
            Part.from_text(
                text=prompt,
            ),
        ],
        config=GenerateContentConfig(
            temperature=0,
            response_mime_type=mimetype.json,
            response_schema=response_type,
        ),
    )
    return response_type.model_validate_json(response.text)


class WhereInfoIsFound(BaseModel):
    page_idx: int = Field(..., description="Page index (based on python indexing which starts with Zero) of page where the information is found in PDF.")
    coordinates: List[int] = Field(..., description="Coordinates (within the page) of relevant information found text. This must be in [ymin, xmin, ymax, xmax] format.")

    

class QuotationSecurityInfo(BaseModel):
    symbol: str
    security_type: str
    issued_securities: int
    issue_date: str = Field(..., description="Date in 'YYYY-MM-DD' format")
    found_location: WhereInfoIsFound = Field(..., description="Information about where exactly the information is found.")
    # page_idx: int = Field(..., description="Page index (based on python indexing which starts with Zero) of page where the information is found in PDF.")
    # cordinates: List[int] = Field(..., description="Coordinates (within the page) of relevant information found text")

class AnnouncementInfo(BaseModel):
    company_name: str
    securities: List[QuotationSecurityInfo]

pdf_path = Path(r"02926729.pdf")
response = await extract_pdf_content(
    pdf_path,
    prompt="Inspect the PDF file of financial annoucements and retrieve information about what was issued",
    response_type=AnnouncementInfo
)
# response
print(response.model_dump_json(indent=4))
```

**Comment by santokalayil** [comment]
`pyproject.toml`

```toml
[project]
name = "sangemini"
version = "0.1.0"
description = ""
authors = [
    {name = "Your Name",email = "you@example.com"}
]
readme = "README.md"
requires-python = ">=3.13,<4"
dependencies = [
    "nest-asyncio (>=1.6.0,<2.0.0)",
    "google-genai @ git+https://github.com/googleapis/python-genai.git",
    "pdf2image (>=1.17.0,<2.0.0)",
    "fitz (>=0.0.1.dev2,<0.0.2)",
    "pypdf2 (>=3.0.1,<4.0.0)",
    "reportlab (>=4.3.1,<5.0.0)",
    "pycryptodome (>=3.22.0,<4.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"

```
